[package]
name = "resources"
version = "0.1.0"
edition = "2021"

[dependencies]
repository = {path = "../repository"}
domain = {path = "../domain"}
dto = {path = "../dto"}

rocket = {version = "0.5.0-rc.2", features = ["json"]}
serde = "1.0.136"
chrono = "0.4.26"
